# Generated by Django 4.1 on 2024-12-09 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newspapers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_of_experience', models.PositiveIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='redactor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
