# Generated by Django 4.1 on 2024-12-10 04:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newspapers', '0003_alter_newspaper_title_alter_newspaper_topic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspaper',
            name='publishers',
            field=models.ManyToManyField(related_name='newspapers_publishers', to=settings.AUTH_USER_MODEL),
        ),
    ]
